# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 960cb2897851297578ebe4d6d70091dca4bc594ef3388af8970ebf502a2cbdc5c127db6077efdfd19967b07d2f6c9452c1e653c3567cecb08ed71ccaa03f04e8

test:
  secret_key_base: 9e8e761a5f502f2d5727da35e494823c39f99b6172e514253b0d9a3857282a5f237d8726532e65bbdc57890d0540fdcdf4f6f7ae767254694a73615a35ddbb97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
